### ISSUE TITLE
Error when running pymethyl-preprocess create_sample_sheet for GSE81961 example

### ISSUE THREAD

**Issue by AlexanderTitus** [Christensen-Lab-Dartmouth/PyMethylProcess#1]
I ran:
pymethyl-preprocess create_sample_sheet -is ./geo_idats/GSE81961_clinical_info.csv -s geo -i geo_idats/ -os geo_idats/samplesheet.csv -d "disease state:ch1" -c include_col.txt

And got:
Please move all other sample sheets out of this directory.
Please remove ./geo_idats/GSE81961_clinical_info.csv from geo_idats/, if it exists in that directory.

Any idea what I need to change?

**Comment by jlevy44** [comment]
Okay @AlexanderTitus , should be released in the next update.

**Comment by jlevy44** [comment]
Just added next steps to the printed statement.

**Comment by jlevy44** [comment]
I'll release a PyPI and Docker update soon when enough changes have been made.
