### ISSUE TITLE
Is preprocessing Supervised or Unsupervised

### ISSUE THREAD

**Issue by shucon** [Christensen-Lab-Dartmouth/PyMethylProcess#12]
Hello @jlevy44 Thanks for the awesome tool. This is not an issue but a query. Is the preprocessed data, dependent or independent from the labels provided in the samplesheet file?

Thanks in advance.

**Comment by jlevy44** [comment]
Hi @shucon, it is not necessary to choose a label from the sample sheet, as the preprocessing should not be dependent on this! However, once the data is preprocessed, you can use it for supervised and unsupervised tasks!

**Comment by shucon** [comment]
Thanks for the clarification @jlevy44 .
